Magneto hard fork
hyperledger/besu pull request #2315
Opened 2021-05-22 05:49 UTC by atoulme

Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>

## PR description
Adds the blocks and the changes for the Magneto hard fork.

## Fixed Issue(s)
Fixes #2314 

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-05-22 15:27 UTC, shemnon requested changes
Relevant fork IDs in ForkIdTest.java need to be updated.

2021-05-22 16:36 UTC, shemnon commented on config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
> +    return getOptionalLong("magnetoBlock");
Should be lowercase.

2021-05-22 16:37 UTC, shemnon commented
Also update ProtocolScheduleBuilder#validateClassicForkOrdering, looks to be missing Thanos as well there.

2021-05-22 22:45 UTC, atoulme commented
Thanks Danno, addressed your comments now.

2021-05-22 22:57 UTC, shemnon commented
This test _should_ keep it from occurring again if we follow the pattern of ^F old fork block->do what was there.

https://github.com/hyperledger/besu/pull/2317

2021-05-22 23:02 UTC, atoulme commented
Let's get #2317 in first.

2021-05-22 23:06 UTC, shemnon approved these changes

2021-05-23 01:06 UTC, atoulme commented
Merged #2317 into this PR.

2021-05-23 03:19 UTC, merged