Prioritize with nonce distance
hyperledger/besu pull request #2505
Opened 2021-07-06 20:24 UTC by jflo

## PR description

Prevent multiple transactions from the same address from evicting others which are waiting in a full transaction pool. When we have to evict a transaction from a full pool, we now also consider how far it is from the lowest nonce from the same address already in the pool. We are also increasing the size of the pending transaction pool, so it should support the new 10MB maximum message size previously introduced by pr [#2485](https://github.com/hyperledger/besu/pull/2485) .

## Fixed Issue(s)

## Changelog
Default value for `--tx-pool-max-size`  is now 32K.
- [X] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-07-07 08:38 UTC, matkt requested changes
Some comments

2021-07-07 08:38 UTC, matkt commented on ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
> +    TransactionsForSenderInfo inPool = transactionsBySender.get(incomingTx.getSender());
I think we have final here

2021-07-07 08:38 UTC, matkt commented on ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
> +    if (inPool == null) { // nothing in pool, you're next
are we sure we can have only a null but not empty inPool ?

2021-07-08 08:08 UTC, matkt approved these changes
LGTM

2021-08-12 18:17 UTC, garyschulte commented on besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
> +    serviceImpl.removeTransactionDroppedListener(id);
nice catch.

2021-08-12 18:24 UTC, garyschulte approved these changes
🚢

2021-08-12 18:40 UTC, merged