clarify logic determining whether a tx is private
hyperledger/besu pull request #2609
Opened 2021-08-03 23:17 UTC by macfarla

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Clarify isGoQuorumPrivateTransaction method. v value is set directly for GoQuorum private transactions, and they don't have a chainId. All other tx derive their v value from the chainId.

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-08-03 23:26 UTC, garyschulte approved these changes
LGTM!

2021-08-03 23:41 UTC, lucassaldanha requested changes
We also need to fix the TransactionPool.

https://github.com/hyperledger/besu/blob/main/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java#L294-L297

It would be better to consolidate the logic into a single place.

2021-08-04 00:14 UTC, macfarla commented
> We also need to fix the TransactionPool.
> 
> https://github.com/hyperledger/besu/blob/main/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java#L294-L297
> 
> It would be better to consolidate the logic into a single place.

Updated. And added a TransactionPool test. Thanks @lucassaldanha

2021-08-04 00:23 UTC, lucassaldanha approved these changes

2021-08-04 00:34 UTC, merged