When tls is on, use passthrough framer and passthrough handshaker to avoid double encryption
hyperledger/besu pull request #3008
Opened 2021-11-04 19:39 UTC by perusworld

When tls is on, use passthrough framer and passthrough handshaker to avoid double encryption

Signed-off-by: Saravana Perumal Shanmugam <perusworld@linux.com>

2021-11-04 19:52 UTC, atoulme commented
By passthrough, do you mean unencrypted? Would you please look at renaming passthrough to “plain”?

2021-11-05 05:49 UTC, lucassaldanha requested changes
PR is looking good. However, there are a few things that we need to fix:
1. All **new** files need to have the updated license header (example: https://github.com/hyperledger/besu/blob/main/consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorModeTransitionLogger.java)
2. Could you please add a changelog entry?

I have also added a few minor comments but the main reason for requesting changes is the license header issue.

2021-11-05 05:49 UTC, lucassaldanha commented on ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainFramer.java
> +    LOG.trace("Init");
NIT suggestion
```
LOG.trace("Initialising PlainFramer");
```

2021-11-05 05:49 UTC, lucassaldanha commented on ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainFramer.java
> +    LOG.trace("deframe");
NIT suggestion
```
LOG.trace("Deframing message");
```

2021-11-05 05:49 UTC, lucassaldanha commented on ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainFramer.java
> +    LOG.trace("frame");
NIT suggestion
```
LOG.trace("Framing message");
```

2021-11-05 05:49 UTC, lucassaldanha commented on ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainMessage.java
> +  }
```suggestion
  public PlainMessage(final MessageType messageType, final byte[] data) {
    this(messageType, Bytes.wrap(data));
  }
```

2021-11-05 05:49 UTC, lucassaldanha commented on ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainMessage.java
> +  }
```suggestion
  public PlainMessage(final MessageType messageType, final Bytes data) {
    this(messageType, -1, data);
  }
```

2021-11-05 17:18 UTC, atoulme commented
Thank you for addressing my feedback! PR intent looks great to me.

2021-11-05 23:40 UTC, lucassaldanha approved these changes

2021-11-05 23:58 UTC, merged