Removing deprecated hash variable which was used to cache the transaction
hyperledger/besu pull request #3110
Opened 2021-11-26 14:22 UTC by mohitsaxenaknoldus

## PR description

## Fixed Issue(s)

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-11-26 15:54 UTC, mohitsaxenaknoldus commented
> ## PR description
> ## Fixed Issue(s)
#2937 
> ## Changelog
> * [x]  I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-11-29 02:25 UTC, macfarla commented
Looks ok to me @mohitsaxenaknoldus 
However the unit test step is failing because the plugin API hash needs updating as a result of this change:
```
* What went wrong:
Execution failed for task ':plugin-api:checkAPIChanges'.
> For the Plugin APIs the checksum of the project did not match what was expected.
  
  If this is a deliberate change where you have thought through backwards compatibility,
  then update "Expected" for "Calculated" in the appropriate build.gradle as the knownHash for this task.
  Expected   : /M23BAhwqtMpjhcoHDMJvbHyhJ4z39z2jJMWUGOBO14=
  Calculated : iVl4LwulrgbVqYsahA4YvgrMqc22OxBk43hFsoYPA5w=
```

2021-11-29 08:34 UTC, mohitsaxenaknoldus commented
> Looks ok to me @mohitsaxenaknoldus However the unit test step is failing because the plugin API hash needs updating as a result of this change:
> 
> ```
> * What went wrong:
> Execution failed for task ':plugin-api:checkAPIChanges'.
> > For the Plugin APIs the checksum of the project did not match what was expected.
>   
>   If this is a deliberate change where you have thought through backwards compatibility,
>   then update "Expected" for "Calculated" in the appropriate build.gradle as the knownHash for this task.
>   Expected   : /M23BAhwqtMpjhcoHDMJvbHyhJ4z39z2jJMWUGOBO14=
>   Calculated : iVl4LwulrgbVqYsahA4YvgrMqc22OxBk43hFsoYPA5w=
> ```

Oh ok. How can I fix that?

2021-11-29 22:01 UTC, macfarla commented
> > Looks ok to me @mohitsaxenaknoldus However the unit test step is failing because the plugin API hash needs updating as a result of this change:
> > ```
> > * What went wrong:
> > Execution failed for task ':plugin-api:checkAPIChanges'.
> > > For the Plugin APIs the checksum of the project did not match what was expected.
> >   
> >   If this is a deliberate change where you have thought through backwards compatibility,
> >   then update "Expected" for "Calculated" in the appropriate build.gradle as the knownHash for this task.
> >   Expected   : /M23BAhwqtMpjhcoHDMJvbHyhJ4z39z2jJMWUGOBO14=
> >   Calculated : iVl4LwulrgbVqYsahA4YvgrMqc22OxBk43hFsoYPA5w=
> > ```
> 
> Oh ok. How can I fix that?
You have to do exactly what it says in the message above - update the knownHash in plugin-api/build.gradle

2021-11-30 09:39 UTC, macfarla commented on CHANGELOG.md
> +- Removed deprecated hash variable `protected volatile Hash hash;` which was used for private transactions [#3110](https://github.com/hyperledger/besu/pull/3110)
this should be under 21.10.3 since we haven't released that version yet (latest is 21.10.2)

2021-12-17 17:33 UTC, mohitsaxenaknoldus commented
@macfarla Fixed the chandelog, please check now. Sorry for the delays!

2021-12-20 06:38 UTC, macfarla commented
@mohitsaxenaknoldus the changelog entry for this should be moved under the topmost release in the changelog ie 22.1.0-RC2
Also the hash needs updating in 
Build file '/home/circleci/project/plugin-api/build.gradle' line: 53

  If this is a deliberate change where you have thought through backwards compatibility,
  then update "Expected" for "Calculated" in the appropriate build.gradle as the knownHash for this task.
  Expected   : DhISJBKoARZyoiT387UIA7QfcEwyOcIYm17f/fLsJRM=
  Calculated : pDLQUs2Gl9hFV1ecKSacbbfwovrjMf/IBPiY1zkOZlI=

2021-12-20 21:58 UTC, mohitsaxenaknoldus commented
> @mohitsaxenaknoldus the changelog entry for this should be moved under the topmost release in the changelog ie 22.1.0-RC2 Also the hash needs updating in Build file '/home/circleci/project/plugin-api/build.gradle' line: 53
> 
> If this is a deliberate change where you have thought through backwards compatibility, then update "Expected" for "Calculated" in the appropriate build.gradle as the knownHash for this task. Expected : DhISJBKoARZyoiT387UIA7QfcEwyOcIYm17f/fLsJRM= Calculated : pDLQUs2Gl9hFV1ecKSacbbfwovrjMf/IBPiY1zkOZlI=

Done.
Also, here it is showing DCO ok but on CI DCO is failing, why?

2021-12-20 22:08 UTC, macfarla commented
> Also, here it is showing DCO ok but on CI DCO is failing, why?
There's a DCO issue on another branch. We are working on it, should be fixed shortly.

2021-12-21 11:35 UTC, mohitsaxenaknoldus commented
> > Also, here it is showing DCO ok but on CI DCO is failing, why?
> > There's a DCO issue on another branch. We are working on it, should be fixed shortly.

Oh ok, seems to be passing now.

2021-12-21 23:12 UTC, macfarla requested changes

2021-12-21 23:12 UTC, macfarla commented on plugin-api/build.gradle
> +Calculated : pDLQUs2Gl9hFV1ecKSacbbfwovrjMf/IBPiY1zkOZlI=
we don't want to update this bit!

this line is what needs changing:
  knownHash = 'QPxUj/HJM7DZkbUq538/S2f3MmwPOqaPX/BBTkKznQk='

2021-12-23 09:17 UTC, mohitsaxenaknoldus commented
Let's see if it works now @macfarla

2021-12-28 09:14 UTC, mohitsaxenaknoldus commented
Hey @macfarla Is this good to merge now?

2022-01-04 00:56 UTC, macfarla commented
Somehow the hash got overwritten again in a "merge from main" commit. Fingers crossed I've fixed it now! Thanks for your patience with this one @mohitsaxenaknoldus !

2022-01-04 21:13 UTC, taccatisid approved these changes

2022-01-04 21:15 UTC, macfarla approved these changes

2022-01-04 22:19 UTC, merged

2022-01-04 22:20 UTC, macfarla commented
Thanks again for your patience with getting this change merged in @mohitsaxenaknoldus - hopefully your next contribution doesn't hit so many bumps in the road!!