Dockerfile: update to different 11 jre
hyperledger/besu pull request #3137
Opened 2021-12-08 05:08 UTC by macfarla

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Update Dockerfile to use a Java 11 JRE which passes docker scan

## Fixed Issue(s)
Fixes #3045 
## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2021-12-13 06:22 UTC, macfarla commented
Running locally seems to work

```
docker scan -f docker/openjdk-11/Dockerfile hyperledger/besu:21.10.4-SNAPSHOT-openjdk-11 --severity high

Testing hyperledger/besu:21.10.4-SNAPSHOT-openjdk-11...

Organization:      macfarla
Package manager:   deb
Target file:       docker/openjdk-11/Dockerfile
Project name:      docker-image|hyperledger/besu
Docker image:      hyperledger/besu:21.10.4-SNAPSHOT-openjdk-11
Platform:          linux/amd64
Base image:        eclipse-temurin:11-jre
Licenses:          enabled

✓ Tested 144 dependencies for known issues, no vulnerable paths found.
```
and running with `docker run` ->

```
2021-12-13 06:20:52.330+00:00 | EthScheduler-Timer-0 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2021-12-13 06:20:52.332+00:00 | EthScheduler-Timer-0 | INFO  | PivotBlockConfirmer | Confirm pivot block 13795122 with at least 5 peers.
2021-12-13 06:20:52.568+00:00 | nioEventLoopGroup-3-3 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 13795122: 0xfde1e31dfeaea2aa91951c451e26bcd2274243cf62cc21dfe0f6a808e39d19da
2021-12-13 06:20:52.574+00:00 | nioEventLoopGroup-3-10 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 13795122: 0xfde1e31dfeaea2aa91951c451e26bcd2274243cf62cc21dfe0f6a808e39d19da
2021-12-13 06:20:52.580+00:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 13795122: 0xfde1e31dfeaea2aa91951c451e26bcd2274243cf62cc21dfe0f6a808e39d19da
2021-12-13 06:20:52.633+00:00 | nioEventLoopGroup-3-3 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 13795122: 0xfde1e31dfeaea2aa91951c451e26bcd2274243cf62cc21dfe0f6a808e39d19da
2021-12-13 06:20:52.677+00:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 13795122: 0xfde1e31dfeaea2aa91951c451e26bcd2274243cf62cc21dfe0f6a808e39d19da
2021-12-13 06:20:52.688+00:00 | nioEventLoopGroup-3-1 | INFO  | WorldStateDownloader | Begin downloading world state from peers for block 13795122 (0xfde1e31dfeaea2aa91951c451e26bcd2274243cf62cc21dfe0f6a808e39d19da). State root 0x7c65f99dcd70f72af819be3e63253abff4ccffda0e6f6b17fa279b087596e930
2021-12-13 06:20:53.043+00:00 | nioEventLoopGroup-3-3 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x65e70d27ac7aed4132... at block 0
```

2021-12-13 15:50 UTC, shemnon submitted a review, later dismissed
version changes should either be within naming convention or update the naming convention to match the underlying docker image.

2021-12-13 15:50 UTC, shemnon commented on docker/openjdk-11/Dockerfile
> +FROM eclipse-temurin:11-jre
(a) The variant for this docker file is, explicitly by tag and directory name, `openjdk-11`. If the solutionis to stop using openjdk-11 the the tag and directory name should be changed to `eclipse-temurin-11`

(b) There are two other packages using `openjdk:11-jre-slim-buster` in this repo, any patch should also address those two docker images

2021-12-13 15:51 UTC, shemnon requested changes
version changes should either be within naming convention or update the naming convention to match the underlying docker image.

2021-12-14 02:30 UTC, shemnon commented
Alternative proposal: #3171 - change the base linux image.

2021-12-16 03:32 UTC, closed without merging