Add Ryan Jones as non-code maintainer
hyperledger/besu pull request #3359
Opened 2022-02-02 00:54 UTC by lucassaldanha

## Proposal

I propose to add @ryanjjones10 as a Besu non-code maintainer.

@ryanjjones10 has contributed with roadmap planning and categorizing bugs and issues for Besu. Becoming a non-code maintainer, Ryan will be able to label bugs and close relevant tickets, helping to keep the project tidy.

Voting ends two weeks from today.

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

## Other changes

I have also taken this opportunity to fix the ordering in the maintainers list. It is supposed to be alphabetical on the Github handle, not the name.

2022-02-02 00:54 UTC, lucassaldanha commented on MAINTAINERS.md
> +| Ryan Jones       | ryanjjones10     | ryanjjones10     |
This is the only new maintainer added in this PR. Other changes are just shuffling names around.

2022-02-02 01:27 UTC, macfarla commented on MAINTAINERS.md
> +| Simon Dudley     | siladu           | siladu           |
i comes after h @lucassaldanha

2022-02-02 03:26 UTC, frankisawesome approved these changes

2022-02-02 03:55 UTC, garyschulte approved these changes

2022-02-02 05:56 UTC, jframe approved these changes

2022-02-02 08:50 UTC, matkt approved these changes

2022-02-02 09:31 UTC, daniellehrner approved these changes

2022-02-02 16:52 UTC, fab-10 approved these changes

2022-02-02 22:20 UTC, ajsutton approved these changes

2022-02-02 23:33 UTC, macfarla approved these changes

2022-02-03 05:39 UTC, shemnon requested changes
One concern I have is the visibility of Ryan's work.  There are no links to any of the activities that Ryan has contributed. Other maintainers have had a list of notable contributions to their maintainer proposal.

The lack of public visibility raises several issues. As it stands without publicly linkable activity one would not be counted as a contributor for TSC elections, per the hyperledger charter. 
Second, the role of maintainer should be a public one, not a role that provides services in a private setting. It also comes with duties that are impossible to fulfill without a public presence.

If the issue is needing to get github write access for zenhub, that can be granted without elevating someone to the role of maintainer. The mechanics of github should not be conflated with the definition of maintainer in the Hyperledger charter.

2022-02-03 06:08 UTC, ryanjjones10 commented
@shemnon, I certainly agree with you. What is the best way to get the github write access for Zenhub?

Over time, I look to contribute more to Besu in a public setting and will look for ways to do so.

2022-02-03 11:09 UTC, ryjones commented
> @shemnon, I certainly agree with you. What is the best way to get the github write access for Zenhub?

please send email to community-architects@hyperledger.org

2022-02-03 21:17 UTC, jflo requested changes
I agree with Danno. Ryan is a swell guy, and will make great and needed contributions in the near future. However, right now the Maintainer status carries with it responsibilities that aren't really fit for non-committers. Things like reviewing PRs and executing releases.

Ryan, just know that we will find a solution to this to get you involved, and so you have the access you need to organize outstanding issues.

The re-organization of names on the list is fine, that can stay.

2022-02-10 22:28 UTC, lucassaldanha commented
Thanks for the feedback. I'll close this PR and we will try to get the permissions sorted instead of adding Ryan to the maintainers list.

2022-02-10 22:28 UTC, closed without merging

2022-02-11 00:47 UTC, macfarla commented
@lucassaldanha if you've still got it handy can you push a PR with just the reordering on github ID?

2022-02-11 03:00 UTC, lucassaldanha commented
> @lucassaldanha if you've still got it handy can you push a PR with just the reordering on github ID?
Sure!