Lgtm alerts
hyperledger/besu pull request #3413
Opened 2022-02-11 21:33 UTC by macfarla

Fix 4 LGTM alerts 
* close response stream x 3
* check null privacyPluginParams in BesuCommand

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2022-02-14 10:29 UTC, fab-10 requested changes
I have proposed some changes to make clear that Jackson closes the stream, and also improve the closing behavior of `JsonResposeStream` in another PR https://github.com/hyperledger/besu/pull/3421

2022-02-15 04:33 UTC, macfarla commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
> +                final JsonResponseStreamer jsonResponseStreamer =
👍

2022-02-15 04:35 UTC, macfarla commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
> +                final JsonResponseStreamer jsonResponseStreamer =
so LGTM is just plain wrong about this?

2022-02-15 05:13 UTC, macfarla commented
idk why the main besu lgtm isn't working but if I look at "my alerts" it shows this one - is this rule incorrect?
https://lgtm.com/rules/2980072/
![Screen Shot 2022-02-15 at 3 11 54 pm](https://user-images.githubusercontent.com/2627919/153996826-e88ef3b4-f59a-45ae-aa01-4c7971215fe9.png)

2022-02-15 09:12 UTC, fab-10 commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
> +                final JsonResponseStreamer jsonResponseStreamer =
Idk how LGTM works, but it seems that it does not understand that the output stream is managed by Jackson.

2022-02-15 09:13 UTC, fab-10 approved these changes

2022-02-15 09:57 UTC, merged