Fcu verify payload attributes
hyperledger/besu pull request #3837
Opened 2022-05-15 22:19 UTC by daniellehrner

## PR description

Adds payload attributes checks to EngineForkchoiceUpdated and returns INVALID_PAYLOAD_ATTRIBUTES error if any of them should be invalid.

## Fixed Issue(s)
"fixes #3836 "

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2022-06-08 08:24 UTC, daniellehrner commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
> +              .toString());
Thank you for the suggestion, I've changed it

2022-06-08 12:29 UTC, fab-10 requested changes

2022-06-10 09:40 UTC, daniellehrner commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
> +        () -> payloadAttributes.getPrevRandao().toHexString());
I've fixed it. Thank you!

2022-06-10 09:41 UTC, daniellehrner commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
> +
Yes, after further investigation that is how it should work. I've changed the code accordingly

2022-06-10 15:39 UTC, fab-10 approved these changes

2022-06-13 08:40 UTC, merged