Block prop on first final
hyperledger/besu pull request #4265
Opened 2022-08-16 18:08 UTC by jflo

Stops block propagation via devp2p when network finalizes, not at TTD as previous.

2022-08-16 19:37 UTC, garyschulte requested changes
LGTM, minor change and non-blocking ask

2022-08-16 19:37 UTC, garyschulte commented on besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
> +import org.jetbrains.annotations.NotNull;
Did you mean javax.validation.constraints.NotNull ?  the jetbrains annotation only has an effect in the IDE afaik.

2022-08-16 19:37 UTC, garyschulte commented on ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
> +  public void shouldStopWhenFinalized() {
non-blocking, but an additional test that asserts block propagation never starts if we are past TTD would be a good measure.  I don't see a DefaultSynchronizerTest class however.

2022-08-17 05:34 UTC, garyschulte commented
FYI, running hive master against this branch resolves the 4 failing gossip engine-transition tests 👍

2022-08-17 13:43 UTC, fab-10 approved these changes

2022-08-17 18:54 UTC, garyschulte commented on besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
> +import org.jetbrains.annotations.NotNull;
removed per convo with @jflo

2022-08-17 19:48 UTC, merged