Add new RPC endpoints debug_setHead & debug_replayBlock
hyperledger/besu pull request #4580
Opened 2022-10-31 15:01 UTC by daniellehrner

## PR description

`debug_setHead`: Sets the current head of the local chain by block number.
`debug_replayBlock`: Reimports a block by block number, by rolling the head of the local chain back to `blockNumber` - 1 and afterwards importing the given block.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2022-11-06 04:58 UTC, garyschulte requested changes

2022-11-08 12:06 UTC, daniellehrner commented on CHANGELOG.md
> +- Added new RPC endpoints `debug_setHead` & `debug_replayBlock  [4580](https://github.com/hyperledger/besu/pull/4580)
Thanks. I've moved it.

2022-11-08 12:07 UTC, daniellehrner commented on gradle.properties
> -version=22.10.0-SNAPSHOT
I've fixed it.

2022-11-08 12:08 UTC, daniellehrner commented on acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
> +            .jsonRpcDebug()
This is for the acceptance tests only. And only when testing the engine RPC endpoints. Do you think it is a problem to enable debug for those?

2022-11-10 06:23 UTC, macfarla commented on acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
> +            .jsonRpcDebug()
I think for the ATs that's ok

2022-11-10 08:10 UTC, garyschulte approved these changes

2022-11-12 19:41 UTC, merged