merge main into release 22.10.x
hyperledger/besu pull request #4716
Opened 2022-11-21 23:50 UTC by garyschulte

## PR description

update alpha release candidate with current `main`

## Fixed Issue(s)

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2022-11-21 23:51 UTC, jflo approved these changes

2022-11-22 03:35 UTC, macfarla approved these changes

2022-11-22 09:49 UTC, fab-10 requested changes
have you done cherry-picks? I see that the fix for the memory consumption during initial sync is not here

2022-11-22 18:42 UTC, garyschulte commented
> have you done cherry-picks? I see that the fix for the memory consumption during initial sync is not here

It was current with `main` as of yesterday.  I re-cherry-picked and pushed just now.  The output of `git diff origin/main`:

```
diff --git a/gradle.properties b/gradle.properties
index a350ba30e..5d7a54fc3 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,4 +1,4 @@
-version=22.10.1-SNAPSHOT
+version=22.10.1-alpha-SNAPSHOT
 
 org.gradle.welcome=never
 org.gradle.jvmargs=-Xmx1g
```

2022-11-22 19:03 UTC, fab-10 approved these changes

2022-11-22 21:32 UTC, merged