[Work In Progress] Optimize Sstore operation execution time
hyperledger/besu pull request #4836
Opened 2022-12-18 14:06 UTC by ahamlat

Signed-off-by: Ameziane H <ameziane.hamlat@consensys.net>

## PR description

## Fixed Issue(s)

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2022-12-20 19:30 UTC, shemnon requested changes
The CodeQL warnings all appear legitimage, so please address them.

As this is changing an API on an interface it will be a breaking change and will need to land in 23.1.0-beta and not be cherry picked into 22.10.4.
Also, add a changelog entry under breaking changes.

2022-12-22 19:09 UTC, garyschulte commented on evm/src/main/java/org/hyperledger/besu/evm/operation/SStoreOperation.java
> +    final UInt256 newValue = UInt256.fromBytes(frame.popStackItem());
is this rename intentional or leftover from development?

2022-12-22 19:30 UTC, garyschulte approved these changes
:+1:  just one nitpick about omitting final for local variables in gas calculators. Perhaps you had a reason to omit final?

2022-12-22 19:30 UTC, garyschulte commented on evm/src/main/java/org/hyperledger/besu/evm/gascalculator/LondonGasCalculator.java
> +      UInt256 localOriginalValue = originalValue.get();
effectively final, can be final

2022-12-22 19:30 UTC, garyschulte commented on evm/src/main/java/org/hyperledger/besu/evm/gascalculator/IstanbulGasCalculator.java
> +      UInt256 localOriginalValue = originalValue.get();
final again

2022-12-22 20:29 UTC, ahamlat commented on evm/src/main/java/org/hyperledger/besu/evm/gascalculator/LondonGasCalculator.java
> +      UInt256 localOriginalValue = originalValue.get();
done

2022-12-22 20:29 UTC, ahamlat commented on evm/src/main/java/org/hyperledger/besu/evm/gascalculator/IstanbulGasCalculator.java
> +      UInt256 localOriginalValue = originalValue.get();
done

2022-12-22 20:40 UTC, shemnon approved these changes

2022-12-23 17:00 UTC, merged