4844: read blobs as raw bytes not as unit256 and fix blob versioned hashes validation
hyperledger/besu pull request #5071
Opened 2023-02-08 16:51 UTC by fab-10

Signed-off-by: Fabio Di Fabio <fabio.difabio@consensys.net>

## PR description

## Fixed Issue(s)

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [ ] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

2023-02-08 19:20 UTC, jflo approved these changes
minor suggestion, looks good otherwise.

2023-02-08 19:20 UTC, jflo commented on evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java
> +          File jniWillLoadFrom = File.createTempFile("kzgTrustedSetup", "txt");
```suggestion
          File jniWillLoadFrom = File.createTempFile("kzgTrustedSetup", ".txt");
```

2023-02-08 19:46 UTC, jflo commented
Unit tests are failing and it is due to a coredump happening when the new test tries to load the new trusted setup file. If I try to run that test with a known good setup file, it does not coredump.

2023-02-08 19:47 UTC, jflo requested changes
Unit tests are failing and it is due to a coredump happening when the new test tries to load the new trusted setup file. If I try to run that test with a known good setup file, it does not coredump.

2023-02-08 22:27 UTC, gezero approved these changes

2023-02-09 10:56 UTC, fab-10 commented
> Unit tests are failing and it is due to a coredump happening when the new test tries to load the new trusted setup file. If I try to run that test with a known good setup file, it does not coredump.

I did some debug and found that the c-kzg lib does not support mixing `MINIMAL` and `MAINNET` preset in the same process, since each one of them as a standalone native lib, so the test loads first the minimal lib, and when we try to load a mainnet trusted setup used by `aggregateKzgProof` it fails.
I do not know if there is a workaround for this, so for now I am putting ignore on this test

2023-02-10 15:01 UTC, merged