reintroduce checking of block height for certain tasks when we are not PoS (Revert PR#3911)
hyperledger/besu pull request #5083
Opened 2023-02-10 07:01 UTC by pinges

fixes issue #https://app.zenhub.com/workspaces/team-revenant-5e6accf93892a67e1d7a7f34/issues/gh/hyperledger/besu/5061

Signed-off-by: Stefan <stefan.pingel@consensys.net>

2023-02-10 18:37 UTC, fab-10 reviewed
Since I think that info if the network is running on PoS should be in ProtocolSpec, I did a [PR](https://github.com/hyperledger/besu/pull/5085) for that, note that it is not yet complete, since the revert of some minimunRequiredBlockNumber has still to be done, but it should give an idea.
Many files are modified only to pass new constructor params, so the main ones to check are: 
EthPeers, ProtocolSpec and MainnetProtocolSpecs

2023-02-14 13:41 UTC, fab-10 requested changes
looks good, only some code to remove since no more useful

2023-02-14 13:41 UTC, fab-10 commented on ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java
> +                maybeFinalizedHeader.map(BlockHeader::getNumber).orElse(0L),
No need to revert this part, since backward sync is always on PoS, so you can statically set 0 here

2023-02-15 01:34 UTC, macfarla approved these changes
LGTM

2023-02-15 01:36 UTC, merged