remove parallelism from AT task
hyperledger/besu pull request #5231
Opened 2023-03-16 20:51 UTC by macfarla

This task is now only taking 3 minutes with parallelism at 6. If it takes less than unit tests without parallelism there's no need. 

Occasionally seeing this error on 1 of the 6 runners `No tests found for given includes` 
Because for the parallelism, we're still passing all the AT classes into the splitter, it is possible that none of them match
https://app.circleci.com/pipelines/github/hyperledger/besu/21077/workflows/d91f36d9-7103-44c0-887a-46430e0331b9/jobs/129673/parallel-runs/1?filterBy=FAILED

2023-03-16 20:51 UTC, macfarla commented
```
 What went wrong:
Execution failed for task ':acceptance-tests:tests:acceptanceTestMainnet'.
> No tests found for given includes: [**/bft/**, **/clique/**, **/permissioning/**, **/privacy/**](exclude rules) [org.hyperledger.besu.tests.acceptance.jsonrpc.AbstractJsonRpcTest, org.hyperledger.besu.tests.acceptance.bft.BftZeroValidators, org.hyperledger.besu.tests.acceptance.permissioning.NodesSmartContractPermissioningStaticNodesAcceptanceTest, org.hyperledger.besu.tests.acceptance.privacy.contracts.PrivacyGroupTest, org.hyperledger.besu.tests.acceptance.bft.BftAcceptanceTestParameterization, org.hyperledger.besu.tests.acceptance.jsonrpc.JsonRpcWebsocketAuthenticationAcceptanceTest, org.hyperledger.besu.tests.acceptance.privacy.BftPrivacyClusterAcceptanceTest, org.hyperledger.besu.tests.acceptance.privacy.multitenancy.MultiTenancyValidationFailAcceptanceTest, org.hyperledger.besu.tests.acceptance.permissioning.AccountSmartContractPermissioningAcceptanceTestBase, org.hyperledger.besu.tests.acceptance.privacy.PrivCallAcceptanceTest, org.hyperledger.besu.tests.acceptance.privacy.PrivacyClusterAcceptanceTest, org.hyperledger.besu.tests.acceptance.clique.CliqueDiscardRpcAcceptanceTest, org.hyperledger.besu.tests.acceptance.permissioning.NodeSmartContractPermissioningAcceptanceTestBase](--tests filter)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insight
```

2023-03-16 20:57 UTC, macfarla commented
here's another one https://app.circleci.com/pipelines/github/hyperledger/besu/21087/workflows/0806c2c8-911a-43ff-8502-e3a641b88e31/jobs/129736

2023-03-17 00:35 UTC, siladu requested changes
> If it takes less than unit tests without parallelism there's no need.

Is there blocker on improving unit tests duration?

Would rather we keep these tests as fast as is feasible unless there's a reason unit tests with also be slower.

It's still useful to have ATs be fast if you have to rerun that job upon a flaky failure for example.

Will reducing parallelism rather than completely removing it still help with the error?

2023-03-17 00:35 UTC, siladu commented on .circleci/config.yml
> +    executor: besu_executor_xl
what's the difference between these executors, do we need both?

2023-03-17 08:53 UTC, macfarla commented
Alternative approach - reduce parallelism - #5232

2023-03-19 22:47 UTC, macfarla commented
closing in favour of #5234

2023-03-19 22:47 UTC, closed without merging