Fix getAccountProof for Bonsai
hyperledger/besu pull request #5647
Opened 2023-06-28 00:53 UTC by gfukushima

## PR description
This PR fix the eth_getProof RPC method when using Bonsai by adding the worldStateProof to BonsaiWorldStateProvider.
By passing a snapshot of the ws that we want the proof for the BonsaiWorldStateProvider should be able to make normal usage of the worldStateProof to generate the proofs.

## Fixed Issue(s)

Part of #5377

2023-06-29 12:32 UTC, matkt requested changes
seems to be good

do we can add test for bonsai in this class WorldStateProofProviderTest.  the current tests are only using forest

you can use this class as example SnapWorldDownloadStateTest we are using Parameterized to call the same tests with bonsai and forest

2023-07-06 07:26 UTC, siladu commented on ethereum/core/src/test/java/org/hyperledger/besu/ethereum/proof/WorldStateProofProviderTest.java
> +@RunWith(Parameterized.class)
nit: would be preferable to use JUnit 5 syntax if possible

2023-07-06 07:26 UTC, siladu commented on ethereum/core/src/test/java/org/hyperledger/besu/ethereum/proof/WorldStateProofProviderTest.java
> +
```suggestion
    worldStateStorage =
        switch (dataStorageFormat) {
          case BONSAI -> new BonsaiWorldStateKeyValueStorage(
              new InMemoryKeyValueStorageProvider(), new NoOpMetricsSystem());
          case FOREST -> new WorldStateKeyValueStorage(new InMemoryKeyValueStorage());
        };
```

2023-07-06 07:26 UTC, siladu commented on ethereum/core/src/test/java/org/hyperledger/besu/ethereum/proof/WorldStateProofProviderTest.java
> +        });
Why is this necessary?

2023-07-06 13:49 UTC, matkt commented
can we verify this GetProof method (compare with other client ?) from what i see getProof doesn't look good. I worked on this part a long time ago but I have a doubt now

Normally GetProof must return the siblings at each level in order to validate the proof. That doesn't seem like it regarding the code. I implemented a getProof method in another component so we can fix that easily but just wanted to be sure i'm not missing something

IMO it should be L1+L2+X for X

*         o
*        / \
*       o   o (L1)
*       / \
*  (L2)o  x

looking at the code it is L1+L2+X

* (L1)  o
*        / \
* (L2)o   o 
*       / \
*    o  x

2023-07-06 22:25 UTC, siladu commented on ethereum/core/src/test/java/org/hyperledger/besu/ethereum/proof/WorldStateProofProviderTest.java
> +        });
Maybe worth a comment explaining this?

2023-07-26 02:42 UTC, gfukushima commented
I've tested and we do provide the right proofs but there's seems to be an issue for proofs there are not the latest state in bonsai. Will move this PR to draft until I get back to it.

2024-01-11 22:22 UTC, gfukushima commented
Closing this until I get back to it.

2024-01-11 22:22 UTC, closed without merging