Benchmarking in evmtool
hyperledger/besu pull request #5754
Opened 2023-08-04 21:54 UTC by shemnon

## PR description

Add a new benchmarking sub-command to `evmtool`

## Fixed Issue(s)

2023-08-08 21:15 UTC, daniellehrner requested changes
Clarification needed regarding native mod exp command line.

2023-08-08 21:15 UTC, daniellehrner commented on besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NativeLibraryOptions.java
> +  private final Boolean nativeModExp = Boolean.FALSE;
Why was this changed to `FALSE`? Shouldn't we prefer the native one per default?

2023-08-08 21:15 UTC, daniellehrner commented on besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NativeLibraryOptions.java
>            "Per default a native library is used for modexp. "
If the change in line 56 is correct this description needs to be changed to default `false`

2023-08-09 11:00 UTC, daniellehrner approved these changes

2023-08-14 00:53 UTC, macfarla commented on ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/BenchmarkExecutor.java
> +   * Run the benchmark with the speicific args. Execution will be done warmup + iterations times
```suggestion
   * Run the benchmark with the specific args. Execution will be done warmup + iterations times
```

2023-08-16 17:06 UTC, merged