EIP7516 - Add BlobBaseFee opcode to Cancun EVM
hyperledger/besu pull request #5884
Opened 2023-09-15 05:59 UTC by Gabriel-Trintinalia

## PR description
Add BLOBBASEFEE to Cancun EVM

## Fixed Issue(s)
fixes #5869

2023-09-15 06:16 UTC, macfarla approved these changes
LGTM

2023-09-15 11:00 UTC, shemnon requested changes

2023-09-15 11:00 UTC, shemnon commented on evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
> +        checkState(blobGasPrice != null, "Missing message frame blob gas price");
This will break downstream users.  Make the default zero or use `Optional<Wei>` and default it to empty.

2023-09-18 04:32 UTC, shemnon approved these changes

2023-09-18 04:32 UTC, shemnon commented on ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/BenchmarkExecutor.java
> +          .blobGasPrice(Wei.ZERO)
This can be removed.  It will also prove the API is optional.

2023-09-18 10:08 UTC, merged