Store trielog as blobdb
hyperledger/besu pull request #6289
Opened 2023-12-13 07:49 UTC by usmansaleem

## PR description
Store trielog as blobdb to improve performance.

## Fixed Issue(s)

See https://github.com/hyperledger/besu/issues/5866

2024-01-19 01:29 UTC, siladu commented
> If my PR includes database changes (e.g. KeyValueSegmentIdentifier) I have thought about compatibility and performed forwards and backwards compatibility tests

How was this part tested?

2024-01-19 01:32 UTC, siladu commented
@usmansaleem I'm not really sure what the graph in the description is showing, can you add some explanation please?

Also, have a feeling we discussed it last year, but can't remember what the outcome of the following test was?
> Verify if pruning has an impact on performance due to compaction https://github.com/hyperledger/besu/issues/5866

2024-01-19 01:34 UTC, siladu commented
> @usmansaleem I'm not really sure what the graph in the description is showing, can you add some explanation please?

ah, just spotted https://github.com/hyperledger/besu/issues/5866#issuecomment-1899360419

Have you got a graph for the trie log pruning enabled?

---
Last one...

>  Should we have a feature flag for this or should it be enabled by default?

I guess the answer to this was yes?

2024-01-19 01:36 UTC, jframe commented
> Store trielog as blobdb to improve performance. https://github.com/hyperledger/besu/pull/5475 has shown that blobdb is better choice for static data as it reduced the rocksdb write amplifications during compaction. Manually tested upgrade and downgrade.
Do you have a graph on the impact on the engine API FCU and new payload?

2024-01-23 10:00 UTC, fab-10 commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueSegmentIdentifier.java
> +  TRIE_LOG_STORAGE(new byte[] {10}, new int[] {2}, true),
No, RocksDB will start using blobs on new files only

2024-01-23 10:09 UTC, fab-10 requested changes
Since after https://github.com/hyperledger/besu/pull/6445 there can be deletions to this column family, there is the need to enable, and tune, blob garbage collection for it, since now it is it disabled by default (blockchain data cf is meant to be append only with no deletions*)

* there is an experimental feature for pruning the blockchain data as well, so enabling blob garbage collections is useful also there

2024-01-30 17:34 UTC, fab-10 approved these changes
LGTM.
It maybe be required to tune the following two options if the trielog purge is enabled and the space is not reclaimed quicky enough (cc @siladu )

- blob_garbage_collection_age_cutoff: the cutoff that the GC logic uses to determine which blob files should be considered “old.” For example, the default value of 0.25 signals to RocksDB that blobs residing in the oldest 25% of blob files should be relocated by GC. This parameter can be tuned to adjust the trade-off between write amplification and space amplification.

- blob_garbage_collection_force_threshold: if the ratio of garbage in the oldest blob files exceeds this threshold, targeted compactions are scheduled in order to force garbage collecting the blob files in question, assuming they are all eligible based on the value of blob_garbage_collection_age_cutoff above. This can help reduce space amplification in the case of skewed workloads where the affected files would not otherwise be picked up for compaction. This option is currently only supported with leveled compactions.

2024-01-31 09:54 UTC, merged