Change 'limit' from a required parameter to an optional parameter
hyperledger/besu pull request #6708
Opened 2024-03-11 09:25 UTC by MASDXI

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Most advanced CI tests are deferred until PR approval, but you could:

- [ ] locally run all unit tests via: `./gradlew build`
- [ ] locally run all acceptance tests via: `./gradlew acceptanceTest`
- [ ] locally run all integration tests via: `./gradlew integrationTest`
- [ ] locally run all reference tests via: `./gradlew ethereum:referenceTests:referenceTests`

## PR description
Enhancement `TX_POOL` API `txpool_besuPendingTransactions` by changing 'numResults' from a required parameter to an optional parameter.  if the parameter `limit` does not exist will use pending transactions size as a limit.

## Fixed Issue(s)
fixes #6707

2024-03-13 04:28 UTC, macfarla approved these changes
LGTM - @fab-10 any comments?

2024-03-13 17:55 UTC, fab-10 requested changes
The change makes sense, a couple of suggestions and please add unit tests to validate the change.

Note that since the txpool could contain many MB of data, and if requesting all txs, it is still possible that are limits elsewhere (HTTP, proxies, etc...) that could prevent to get the full response

2024-03-13 17:55 UTC, fab-10 commented on CHANGELOG.md
> +- `txpool_besuPendingTransactions`change parameter `limit` to optional parameter [#6708](https://github.com/hyperledger/besu/pull/6708)
Name the parameter as per documentation https://besu.hyperledger.org/public-networks/reference/api#parameters-92

```suggestion
- `txpool_besuPendingTransactions`change parameter `numResults` to optional parameter [#6708](https://github.com/hyperledger/besu/pull/6708)
```

2024-03-13 17:55 UTC, fab-10 commented on ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TxPoolBesuPendingTransactions.java
> +    final Collection<PendingTransaction> pendingTransactions =
to avoid fetching twice all the txs in the pool, that could be a costly operation, reuse `pendingTransactions` below at line 64

2024-03-14 09:12 UTC, fab-10 approved these changes

2024-03-14 09:40 UTC, merged