Peering - disconnects refactor
hyperledger/besu pull request #6968
Opened 2024-04-19 02:51 UTC by macfarla

## PR description
Before this PR, when we get to max peers, we refuse ALL incoming connections regardless of any properties of the incoming peer (with UNKNOWN reason). There were a few spots where we were disconnecting peers for various reasons including repeated timeouts and "useless" responses. This PR aims to consolidate the disconnects, as well as only disconnecting an established peer when we have a better peer to replace it with.

* Move the disconnection decision from PeerReputation/Peer to EthPeers so the totality of current peers can be considered.
* use reputation score to sort peers within EthPeers (bestPeerComparator)
* note in a few places in tests I've explicitly set the comparator to what was used before (uses chain height estimate) to avoid having to update a heap of tests that are dependent on the decision made by the comparator
* only disconnect "worst" peer if we have max peers (think this will help on holesky for "useless" disconnects but not for socket closed etc - where the connection is already gone). 
* on incoming connection, compare the incoming peer to the current collection of peers and (if at max peers) disconnect whichever compares least favourably - in effect this will be the incoming peer if all our current peers are giving us good responses (reputation score), or it will be an existing peer if any are not giving good responses

example debug log (yes there is a TODO to remove this log)
`{"@timestamp":"2024-04-19T00:53:31,297","level":"DEBUG","thread":"nioEventLoopGroup-3-9","class":"EthPeers","message":"comparing worstCurrentPeer PeerId: 0x024e106a70572288... PeerReputation score: 87, timeouts: {3=5}, useless: 0, validated? true, disconnected? false, client: erigon/v2.58.2-125509e4/linux-amd64/go1.21.8, [Connection with hashCode 1276176835 inboundInitiated? true initAt 1713481827797], enode://024e106a70572288701e97724610d120a682f69f24881eeee0ab1f6379646780d93daf11d9226593faf71deb699f24020dbecf801eb3d0da779ef2be641590fa@3.38.172.157:30304 with connectingPeer PeerId: 0x1ec3a5e247e616a3... PeerReputation score: 100, timeouts: {}, useless: 0, validated? true, disconnected? false, client: Nethermind/v1.25.4+20b10b35/linux-x64/dotnet8.0.2, [Connection with hashCode 1951644955 inboundInitiated? false initAt 1713488011205], enode://1ec3a5e247e616a347038b9c35a1328529bdf354408fe3c968433df542eb1b2a7c7d1b7b7d481a5b6465baac64877ee53e1396ddf43a3ad0f5f0adbaed659145@188.40.67.160:30303","throwable":""}`

Have seen decent results on holesky and mainnet. Will post some screenshots

There are still a couple of test failures - BlockPropagation tests. Wanted to post this before I have to be AFK for a few hrs

## Fixed Issue(s)
Refs #6805 and #6842

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

2024-04-19 02:54 UTC, macfarla commented
3 x mainnet nodes
1 is a bit flat
![Screenshot 2024-04-19 at 12 53 51 PM](https://github.com/hyperledger/besu/assets/2627919/8d662e5a-e826-479a-9ef4-392316e171ef)

2024-04-19 02:56 UTC, macfarla commented
3 x holesky 
![Screenshot 2024-04-19 at 12 55 44 PM](https://github.com/hyperledger/besu/assets/2627919/3bad94da-d0b4-49aa-992b-b1fe18b13271)

2024-05-05 17:50 UTC, Beanow commented
As mentioned in #6945 do see a lot less UNKNOWN disconnects once hitting our peer limit.

![image](https://github.com/hyperledger/besu/assets/497556/7f18daa7-618e-4d5e-a60d-c799d14f4af9)
Holesky here.

2024-05-22 00:49 UTC, macfarla commented
burn-in of 10 bonsai/checkpoint mainnet nodes (started in 2 batches)
<img width="840" alt="Screenshot 2024-05-22 at 10 46 39 AM" src="https://github.com/hyperledger/besu/assets/2627919/a06cd962-b4d7-48ec-9206-628c1eff696c">

2024-05-22 00:53 UTC, macfarla commented
peering graph from the first batch of mainnet nodes 
<img width="836" alt="Screenshot 2024-05-22 at 10 51 41 AM" src="https://github.com/hyperledger/besu/assets/2627919/ded93389-2edb-4d90-a5ad-77ed4501c713">

and the second
<img width="844" alt="Screenshot 2024-05-22 at 10 52 35 AM" src="https://github.com/hyperledger/besu/assets/2627919/294e0835-2331-44b4-aeb0-fd5beb073b85">

2024-06-05 06:38 UTC, pinges requested changes

2024-06-05 06:38 UTC, pinges commented on ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingSwitchingPeerTask.java
> +    // TODO this duplicates EthPeers.disconnectWorst
Looking at line 141, I think we could just not filter on !is.disconnected?

2024-06-27 01:44 UTC, macfarla commented
<img width="830" alt="Screenshot 2024-06-27 at 11 43 22 AM" src="https://github.com/hyperledger/besu/assets/2627919/0c51ba86-af51-40d2-9267-b4b334ef31a5">
around 1h for all mainnet nodes to get to 100% peers

2024-06-27 01:45 UTC, macfarla commented
<img width="843" alt="Screenshot 2024-06-27 at 11 41 25 AM" src="https://github.com/hyperledger/besu/assets/2627919/760985e1-20f9-48ff-8ccf-627c810e180e">
syncing progress

2024-08-19 23:39 UTC, macfarla commented
@pinges I have made the changes you requested, can you review

2024-09-15 21:50 UTC, macfarla commented
going to close this and reprise the worthy changes into separate PRs

2024-09-15 21:50 UTC, closed without merging