Authcall
hyperledger/besu pull request #7028
Opened 2024-05-01 11:39 UTC by jflo

- adds AUTH and AUTHCALL opcodes to Prague evms.
- adds a mutable authorizedBy:Address field to the MessageFrame
- adds AUTH opcode costing to gas calculators

2024-05-01 14:53 UTC, shemnon requested changes

2024-05-01 14:53 UTC, shemnon commented on evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
> +    registry.put(new AuthOperation(gasCalculator));
Ad a comment referring to the EIP these are for (like in registerCancunOperations)

2024-05-01 14:53 UTC, shemnon commented on evm/src/main/java/org/hyperledger/besu/evm/operation/AuthCallOperation.java
> +      return new OperationResult(cost(frame, true), null);
Failures should push `frame.pushStackItem(LEGACY_FAILURE_STACK_ITEM);` (i.e. zero) to the stack prior to returning an `OperationResult`

2024-05-01 14:53 UTC, shemnon commented on evm/src/test/java/org/hyperledger/besu/evm/operations/AuthOperationsTest.java
> +  public void authCallHappyPath() {
* Needs failure case
* Both need to assert the top stack value is 1 (success) or 0 (failure)

2024-05-07 13:47 UTC, shemnon commented on evm/src/main/java/org/hyperledger/besu/evm/operation/AuthCallOperation.java
> +    super(0xF7, "AUTHCALL", 7, 1, gasCalculator);
FYI this  and AUTH conflicts with an EOF allocated opcode.  Fun times ahead.

2024-05-07 13:49 UTC, shemnon approved these changes
Have any official reference test vectors been published?

2024-05-07 13:50 UTC, jflo commented
> Have any official reference test vectors been published?

Nope. Am keeping an eye out for them, and will be running them asap.

2024-05-07 13:51 UTC, merged