Issue 7273 geth style genesis
hyperledger/besu pull request #7609
Opened 2024-09-12 15:23 UTC by cloudspores

## PR description

## Fixed Issue(s)
Fixes #7273 
Allowing Besu to parse a Geth-style genesis like other clients, so interoperability testing and multi-client network operation is simpler.

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

2024-09-19 12:06 UTC, fab-10 requested changes
Overall looks good, there are some minor things to remove or change.
For the tests, I suggest to add also some real world geth genesis files, for example from the current [Pectra devnets](https://github.com/ethpandaops/pectra-devnets/tree/master/network-configs/devnet-3/metadata), where `genesis.json` is in geth format and `besu.json` is in Besu

2024-09-23 12:44 UTC, cloudspores commented on config/src/main/java/org/hyperledger/besu/config/GenesisFileAnalyzer.java
> +    }
I did more research of the extraData formatting and as far as I can see, the Geth-style formatting of extraData for Clique is the same as for Besu-style.

2024-09-23 12:45 UTC, cloudspores commented on gradle/verification-metadata.xml
> +      </component>
I have reverted these changes, thanks.

2024-09-23 16:15 UTC, fab-10 reviewed
Nice to have the test against real world genesis files.

Before approving I would like to understand potential performance penalty of the extra parsing, see my comment https://github.com/hyperledger/besu/issues/7273#issuecomment-2368714262

2024-09-23 18:47 UTC, cloudspores commented on CHANGELOG.md
> +- Let Besu parse configs in the same way as other clients, so interoperability testing and multi-client network operation is simpler
Fixed, I thought was referring to the check in command.

2024-11-08 16:14 UTC, fab-10 commented
I can take care of this one, evaluating the performance impact

2024-12-24 02:01 UTC, closed without merging