dont' activate flight recorder dumps by default, RIP my ssd
hyperledger/besu pull request #7692
Opened 2024-09-30 15:10 UTC by jflo

Removes enabling .jfr capture on every process started by acceptanceTest targets. This can still be added via any other target, or even explicitly via command line per-run.

2024-09-30 15:18 UTC, ahamlat requested changes

2024-09-30 15:18 UTC, ahamlat commented on build.gradle
> -    "-XX:StartFlightRecording,dumponexit=true,settings=default.jfc",
I recommend to keep it but remove only dumponexit=true, to not dump the file when the process stops or crashes.

2024-09-30 22:43 UTC, pinges approved these changes
LGTM

2024-10-01 05:33 UTC, macfarla approved these changes

2024-10-01 12:16 UTC, ahamlat approved these changes

2024-10-01 12:16 UTC, merged