Update to new version of jc-kzg-4844 lib
hyperledger/besu pull request #7849
Opened 2024-11-02 19:20 UTC by vaidikcode

Signed-off-by: vaidikcode <vaidikbhardwaj00@gmail.com>

## PR description
Updated all the related dependencies 
## Fixed Issue(s)

fixes #7848 

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

2024-11-04 02:09 UTC, siladu reviewed
Hi @vaidikcode can you outline any testing you have done for this please? 
I am wondering if we need to check there isn't a performance regression.

2024-11-04 02:14 UTC, siladu commented
From https://github.com/ethereum/c-kzg-4844/releases/tag/v2.0.0 sounds like there could be some negative memory impact along with the speed improvement

> Compared to precompute=0, precompute=8 is ~75% faster but uses 96 MiB of memory.

2024-11-04 04:13 UTC, vaidikcode commented
Hi @siladu ,
I didn't pay much attention to the precompute value when I updated the dependency; I followed the recommendation from the official dependency website. However, now that you've mentioned it, I realize it could significantly impact memory usage. What do you think I should do next?

2024-11-04 11:29 UTC, fab-10 commented
Teku already did the update https://github.com/Consensys/teku/pull/8651, so we can ask to @StefanBratanov insight about the possible memory impact

2024-11-04 11:55 UTC, StefanBratanov commented
> Teku already did the update [Consensys/teku#8651](https://github.com/Consensys/teku/pull/8651), so we can ask to @StefanBratanov insight about the possible memory impact

This value is for peerDAS, I was told to have the same memory footprint as previously ckzg versions should set the value to 0.

2024-11-04 13:48 UTC, jflo requested changes
I'd like to put this on hold till we can verify the dependency via verification-metadata.xml

2024-11-04 15:30 UTC, jflo approved these changes
confirmed, this looks good thanks

2024-11-05 06:25 UTC, siladu commented
@vaidikcode there's some failing tests, could you try to reproduce locally please?

2024-11-05 08:40 UTC, vaidikcode commented
@siladu working on it

2024-11-05 09:06 UTC, fab-10 requested changes
Remove the version where not needed, and according to the `c-kzg-4844` [changelog](https://github.com/ethereum/c-kzg-4844/releases/tag/v2.0.0)

> The trusted setup format has been updated to include G1 points in monomial form.

    This version of c-kzg-4844 requires the new trusted setup file.
    The new trusted setup file can be used with previous versions of c-kzg-4844.
    Download the new file from [trusted_setup.txt](https://github.com/ethereum/c-kzg-4844/blob/4b915a6617a85ef8c49d456374c1bc7f8647d968/src/trusted_setup.txt) in this repository.
    This should match [trusted_setup_4096.json](https://github.com/ethereum/consensus-specs/blob/13ac373a2c284dc66b48ddd2ef0a10537e4e0de6/presets/mainnet/trusted_setups/trusted_setup_4096.json) in the specifications.
    
  So I expect that the trusted setup file should be update as well, @StefanBratanov was that the case in Teku?

2024-11-05 09:06 UTC, fab-10 commented on evm/build.gradle
> +  implementation 'io.consensys.protocols:jc-kzg-4844:2.0.0'
the version is defined in the `platform` project, so it needs to be removed here

2024-11-05 09:06 UTC, fab-10 commented on besu/build.gradle
> +  implementation 'io.consensys.protocols:jc-kzg-4844:2.0.0'
remove the version

2024-11-05 09:06 UTC, fab-10 commented on ethereum/core/build.gradle
> +  implementation 'io.consensys.protocols:jc-kzg-4844:2.0.0'
remove the version

2024-11-07 04:41 UTC, StefanBratanov commented
> Remove the version where not needed, and according to the `c-kzg-4844` [changelog](https://github.com/ethereum/c-kzg-4844/releases/tag/v2.0.0)
> 
> > The trusted setup format has been updated to include G1 points in monomial form.
> 
> ```
> This version of c-kzg-4844 requires the new trusted setup file.
> The new trusted setup file can be used with previous versions of c-kzg-4844.
> Download the new file from [trusted_setup.txt](https://github.com/ethereum/c-kzg-4844/blob/4b915a6617a85ef8c49d456374c1bc7f8647d968/src/trusted_setup.txt) in this repository.
> This should match [trusted_setup_4096.json](https://github.com/ethereum/consensus-specs/blob/13ac373a2c284dc66b48ddd2ef0a10537e4e0de6/presets/mainnet/trusted_setups/trusted_setup_4096.json) in the specifications.
> ```
> 
> So I expect that the trusted setup file should be update as well, @StefanBratanov was that the case in Teku?

Yes. It was updated. The new one is in the repo itself.

2024-11-07 11:17 UTC, vaidikcode commented
I followed the instructions to update the trusted setup, but the build still fails, and I am unable to identify the issue.

2024-11-07 11:35 UTC, fab-10 commented
something in the native code

```
----------- Stack Backtrace -----------
free+0x1e (0x00007F09DF6A53FE [libc.so.6+0xa53fe])
free_trusted_setup+0x2a (0x00007F09CCFCB6EA [libckzg4844jni.so+0xe6ea])
Java_ethereum_ckzg4844_CKZG4844JNI_loadTrustedSetup__Ljava_lang_String_2J+0x101 (0x00007F09CCFC39F1 [libckzg4844jni.so+0x69f1])
ffi_call_unix64+0x52 (0x00007F09DF01424A [libj9vm29.so+0x21424a])
ffi_call_int+0x1a1 (0x00007F09DF0133E1 [libj9vm29.so+0x2133e1])
_ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x11718 (0x00007F09DEEB6AB8 [libj9vm29.so+0xb6ab8])
bytecodeLoopCompressed+0xca (0x00007F09DEEA538A [libj9vm29.so+0xa538a])
 (0x00007F09DEFA0922 [libj9vm29.so+0x1a0922])
---------------------------------------
```

2024-11-10 09:52 UTC, vaidikcode commented
Do i need to update these files and if yes how 
[https://github.com/hyperledger/besu/tree/main/config/src/main/resources/kzg-trusted-setups](url)

2024-11-10 09:58 UTC, vaidikcode commented
Do i need to update these files too? if yes how
config/src/main/resources/kzg-trusted-setups

2024-11-10 09:59 UTC, vaidikcode commented
Do i need to update these files too? 
[config/src/main/resources/kzg-trusted-setups](URL)
If yes how?

2024-11-10 10:02 UTC, vaidikcode commented
Do i need to update the files in
config/src/main/resources/kzg-trusted-setups
?

2024-11-10 10:04 UTC, vaidikcode commented
Do i need to update these files too?
[Directory Name](https://github.com/hyperledger/besu/tree/main/config/src/main/resources/kzg-trusted-setups)
if yes how?

2024-11-24 12:47 UTC, vaidikcode commented
@fab-10 do i  need to update the above mentioned files too?

2024-11-25 15:34 UTC, fab-10 commented
@vaidikcode sorry I haven't too much time to look into this now, will check later what it is needed

2025-02-14 16:25 UTC, fab-10 commented
> Do i need to update these files too? [Directory Name](https://github.com/hyperledger/besu/tree/main/config/src/main/resources/kzg-trusted-setups) if yes how?

@vaidikcode I finally have some time, let me know if you still want to work on this, in case the answer to your question is yes, and you can remove `holesky.txt` since it is not used, and in `mainnet.txt` you put the same content of `trusted-setup.txt`

2025-02-15 08:59 UTC, vaidikcode commented
Yes, I want to continue working on this. For now, I have done as instructed and am trying to run tests locally to resolve build failures.

2025-02-18 18:35 UTC, fab-10 commented
@vaidikcode I was looking at the failing test and I found that we have the `mainnet.txt` defined in 2 places, so we should:

1. remove `config/src/main/resources/kzg-trusted-setups/mainnet.txt`
2. update `evm/src/main/resources/kzg-trusted-setups/mainnet.txt` with the new trusted setup

could you apply these changes?

2025-02-19 16:34 UTC, fab-10 approved these changes

2025-02-19 16:34 UTC, fab-10 commented on CHANGELOG.md
> +- Update the jc-kzg-4844 dependency from 0.4.0 to 2.0.0, which is now available on Maven Central [#7849](https://github.com/hyperledger/besu/pull/7849)
```suggestion
- Update the jc-kzg-4844 dependency from 1.0.0 to 2.0.0, which is now available on Maven Central [#7849](https://github.com/hyperledger/besu/pull/7849)
```

2025-02-19 17:00 UTC, merged