7582: Add naive RLP caching for BlockHeader, Transaction, and Withdrawal
hyperledger/besu pull request #7988
Opened 2024-12-05 03:49 UTC by Matilda-Clerke

## PR description
Add naive RLP caching for BlockHeader, Transaction, and Withdrawal. This PR currently ignores Block, BlockBody, and TransactionReceipt due to complexity.

## Issue
https://github.com/hyperledger/besu/issues/7582

2024-12-05 09:53 UTC, fab-10 commented
I see the potential benefit of the caching, but since this is a tradeoff between compute and memory, have you done benchmarks to quantify the performance benefit of the change, and the possible impact on memory?

2024-12-08 23:20 UTC, Matilda-Clerke commented
> I see the potential benefit of the caching, but since this is a tradeoff between compute and memory, have you done benchmarks to quantify the performance benefit of the change, and the possible impact on memory?

Fair point. I modified the BlockHeadersMessageTest locally to produce 10000 headers and timed the looped writeTo calls in BlockHeadersMessage. The original code performed the 10000 writeTo calls in 18 to 23ms, while the updated code performed the 10000 writeTo calls in 13 to 18ms. In terms of memory, it should roughly double the footprint of a header produced from the readFrom method in memory, but these headers should mostly only exist for a short time between being received from a peer, and being stored in the blockchain, after which point the garbage collector should remove the headers as they are no longer referenced.

Do you think the reduction in execution time is worthwhile?

2024-12-09 10:59 UTC, fab-10 commented
So the micro benchmark test confirm that there is a gain on the compute side, and that is worth exploring more, for that I suggest to run some real sync on mainnet with this change and compare the results against some control instances.

2024-12-09 11:14 UTC, ahamlat commented
> it's actually just using indexes to the original underlying array, so it should only be a small amount of extra memory used.

Agreed, but those references will keep strong links to the underlying byte arrays preventing it from garbage collection. I would like to have a rationale on what this feature is going to improve. It is an interesting improvement but is there is real use case for it ? and if so, we need to evaluate, how much is the latency improvement for how much overhead in terms of memory ?

2024-12-11 04:50 UTC, Matilda-Clerke commented
From the micro benchmark, we'd expect a time saving of around 10 seconds for 10 million block headers. Realistically, not a noticeable gain on our current 20+ hour sync. However, it should give us a small saving of CPU utilisation.

Memory breakdown is as follows:
4 bytes to reference the Optional
4 bytes to reference ArrayWrappingBytes
4 bytes to reference the array (reference, not a copy)
4 bytes to store the offset in the array which the ArrayWrappingBytes instance is focusing on
4 bytes to store the length of the array which the ArrayWrappingBytes instance is focusing on
20 bytes per header total additional memory

Regarding garbage collection: If the headers are currently getting garbage collected (I'd expect they are,  but not sure), these references won't prevent the underlying array from being garbage collected.

For this PR, I was looking just for some potential quick wins while continuing to focus mainly on my refactoring of peer tasks. @pinges is working on a more compilcated scheme which manages to avoid decoding the RLP for large portions of the block body in addition to avoiding re-encoding as we're doing here.

2024-12-12 23:45 UTC, Matilda-Clerke commented
Backed out the withdrawal changes as we discussed and don't believe the changes will ever be used.

2024-12-13 08:59 UTC, ahamlat commented
> 4 bytes to reference the Optional

Consider using JOL (Java Object Layout) or a heap dump to have more accurate numbers. With CompressedOOPs enabled, each Java object has a header of 12 Bytes if the JVM heap < 32 GiB or 16 Bytes if JVM heap >= 32 GiB. Depending on the total number of bytes for each object, there is internal and external padding to make the size a multiple of 8.

> 20 bytes per header total additional memory

I think we should focus on the RLP raw data, the underlying byte array, not the headers. The current calculation focuses more on the shallow size because it is deterministic, and takes into account only the headers and the references. With the RPL stored in the transaction, we need to evaluate the impact on the transactionPool in terms of memory usage and garbage collection.

2024-12-19 01:45 UTC, Matilda-Clerke commented
Here's a BlockHeader from a heap dump
![image](https://github.com/user-attachments/assets/6e22f9d5-f503-448f-9005-cf00194d28d0)
I'm not sure exactly how to read this (e.g. the integers don't have a size listed, are they included in their parent instance's size?), but it seems like double digits of extra bytes per header or transaction. What do you think?

2024-12-19 01:49 UTC, Matilda-Clerke commented
We can see from the references on the underlying byte array that it is being reused across many ArrayWrappingBytes instances, including the new rawRlp references
![image](https://github.com/user-attachments/assets/072ee9c5-59fe-4190-b518-56218a01e6df)

2024-12-19 10:57 UTC, ahamlat commented
> I'm not sure exactly how to read this (e.g. the integers don't have a size listed, are they included in their parent instance's size?), but it seems like double digits of extra bytes per header or transaction. What do you think?

In this screenshot below, we can see that the block header is having a reference to a ~2 MBytes byte array (rlp) which I guess is actually the RLP of the block, but that would be a big block, as we can see the offset and the length inside that AbstractWrappingBytes.

![image](https://github.com/user-attachments/assets/932f610e-fb8e-4805-beda-b161b3289b08)

> We can see from the references on the underlying byte array that it is being reused across many ArrayWrappingBytes instances, including the new rawRlp references

I guess all the transactions of that specific block, and the header are referencing the same underlying byte array. Now, we need to evaluate the real memory overhead. To do that, we need to have the number of live blocks in memory during sync and the average of the size of the RLP. You can share a heap dump during sync with your PR. I will extract the numbers.

2025-01-06 16:39 UTC, ahamlat reviewed
I have a suggestion to init RLP during decoding the transaction from the RLP. I think overall, there is no much overhead when I look the heap dump as the underlying byte array is already referenced by the payload of the transaction, and to address.

2025-01-06 16:39 UTC, ahamlat commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
> +        .build();
Using the data I collected from the shared heap dump, the payload field is a subset of the rawRlp field 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/4be1e803-c4cb-475c-b93e-1ae91254ee98" />

**RawRlp**
<img width="1568" alt="image" src="https://github.com/user-attachments/assets/c47796c6-9b38-45b7-b0f5-a2671ced6b98" />

**Payload**
<img width="1568" alt="image" src="https://github.com/user-attachments/assets/27fd0c39-d786-4206-b98a-8e65e45fd5ee" />

2025-01-06 16:39 UTC, ahamlat commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
> +        .build();
On the transaction level, as the payload is already referencing the same underlying byte array, the only overhead is the reference of the rlp

2025-01-07 04:48 UTC, Matilda-Clerke commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
> +        .build();
My only concern in applying this to the transaction encoder/decoder classes is that they seem to only populate a subset of the Transaction fields, so if we try to instead supply in the encoder the full original RLP, it may be significantly larger than it is currently.

What do you think?

2025-01-07 08:16 UTC, ahamlat commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
> +        .build();
There will be no difference, as rawRlp and payload are just references to the same byte array with an offset and a length. It doesn't change the size of the transaction object. With copiedFrom, we lose the first reference of the transaction as we're creating another one. 
The question I didn't investigate is wether we have the (whole) rawRlp of the transaction at this level.

2025-01-08 23:10 UTC, Matilda-Clerke commented
It seems these latest changes aren't quite working right. In particular, a block encoded and written to blockchainStorage is causing RLP errors when being read and decoded. I'm parking this briefly for now to progress some other issues.

2025-01-24 12:08 UTC, fab-10 reviewed
LGTM, just few suggestions.

On the performance side, do you have an estimation on how much this will speed up the initial sync?

2025-01-24 12:08 UTC, fab-10 commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
> +    }
proposing these stylistic changes to remove the Optional, since it make sense that if you `Builder::rawRlp` your intention is to actually set it, otherwise you just do not call the method.
But since the style seems to not be consistent across all fields, feel free to ignore this suggestion and we can postpone the consolidation of the style in another PR

2025-01-24 12:08 UTC, fab-10 commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/AccessListTransactionEncoder.java
> +                });
why this change?

2025-01-27 22:45 UTC, Matilda-Clerke commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/AccessListTransactionEncoder.java
> +                });
I think I probably added logging to try to figure out the issue I was seeing. I'll revert this

2025-01-27 22:45 UTC, Matilda-Clerke commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
> +    }
That makes sense, I'll update the code

2025-01-27 23:29 UTC, Matilda-Clerke commented
@fab-10 I calculated it to shave about 10 seconds off of the sync for block headers

2025-01-28 02:40 UTC, pinges requested changes
Question about all the LOG.trace calls and I found one place where we are potentially doing the wrong thing. Please have a look.

2025-01-28 02:40 UTC, pinges commented on ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java
> +    LOG.trace("Reading long scalar, currentItem = {}", currentItem);
How useful are all these LoOG.trace() calls? Even if the overhead is not big, we are calling these methods a lot!

2025-01-28 22:35 UTC, Matilda-Clerke commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/EIP1559TransactionEncoder.java
> +                    Bytes.concatenate(Bytes.of(transaction.getType().getSerializedType()), rawRlp)),
I'll refactor this a bit. In fact, there was no need to modify these encoder files at all

2025-01-28 22:40 UTC, Matilda-Clerke commented on ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java
> +    LOG.trace("Reading long scalar, currentItem = {}", currentItem);
I found them helpful, but it also seems like there's been very few changes around RLP parsing in the last 8 years. I'll remove them and if anyone needs them in the future, they can always add them back again.

2025-01-30 09:39 UTC, fab-10 approved these changes
LGTM, it would have been nice to have a better impact on reducing syncing time

2025-02-03 01:54 UTC, pinges commented on ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/EIP1559TransactionDecoder.java
> +    RLPInput transactionRlp = input.readAsRlp();
I can see that now :-)

2025-02-03 01:55 UTC, pinges approved these changes
LGTM

2025-02-03 03:51 UTC, merged